title: Sima Bagheri
description: Grapes harvesting season in our [family farm](34°17'24.8"N 49°17'16.3"E)
logo: /assets/img/profile2.png
show_downloads: false
github:
  is_project_page: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
