title: Sima Bagheri
logo: /assets/img/profile2.png
description: I am a MASc student at Concordia Univeristy under supervision of Prof. Lingyu Wang, and Prof. Suryadipta Majumdar. I am also involved as a researcher in NSERC/Ericsson IRC in SDN/NFV Security. Currently, my research project is ACE-WARP, an academic research project that aims to optimize the utilization of non-disruptive attack mitigation solutions.
I am highly interested in machine learning application in security/privacy, threat analysis, offensive security, and usable security/privacy topics.
theme: jekyll-theme-minimal
